### ISSUE TITLE
Can't get groups to work

### ISSUE THREAD

**Issue by pahanakun** [williambl/g-vault#1]
Its probably user error, as I'm not very good at programming, but I can't get the groups to work.

I tried putting the example group with some modifications right inside the square brackets, no luck. I tried another format for yaml lists and no luck. I tried using that other format after running it thru the online parser https://yaml-online-parser.appspot.com/ and no luck.

https://pastebin.com/YTfC0dJC
Whenever I try to connect to the server, the client says "Invalid player data" and the server console shows the errors in the syntax, which I tried to correct in examples 2 and 3 . I'm pretty sure I also tried a modified version of example three where the three lines for the group were all together in one set of {}s as well, and that didn't work.

If you could show how your example group is supposed to be placed in the config file, that would help dummies like myself. Also you could put two or more groups in, just so we can see the syntax for having more than one group.

Other than these problems with groups, the mod still seems to be working fine in 1.18.1!

**Comment by williambl** [comment]
Hi, it should be in one of these formats:
```yaml
# EXAMPLE ONE
vaultCount: 0
doubleChest: true
configGroups: [
{name: amp, vaultCount: 1, doubleChest: yes}
]
 
# EXAMPLE 2
vaultCount: 0
doubleChest: true
configGroups: 
 - name: amp
   vaultCount: 1
   doubleChest: yes
```
